services:
  # 1. ส่วนของ Database (Postgres)
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # 2. ส่วนของ Backend (Django)
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app  # เชื่อมโฟลเดอร์เพื่อให้แก้โค้ดแล้วเปลี่ยนทันที
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}

  # 3. ส่วนของ Frontend (Vue)
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # ป้องกัน node_modules หาย
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # ช่วยให้ Hot Reload ทำงานใน WSL2 ได้ดีขึ้น

volumes:
  postgres_data: